version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: bank-keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./bank-theme:/opt/keycloak/themes/bank-theme:ro

volumes:
  keycloak-data: